### ISSUE TITLE
Display server URL in output

### ISSUE THREAD

**Issue by mohdomama** [HTTP-APIs/hydrus#103]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:

As of now, the server URL is not shown when the script is run.

### Expected Behaviour:

Display URL in the output.
### Do you want to work on this issue ?
Yes

**Comment by chirag-jn** [comment]
That;s not a difficult job. In the main function, you can just print the IP address with the port number.

**Comment by chirag-jn** [comment]
I have solved this issue and created a pull request too.

**Comment by mohdomama** [comment]
@chirag-jn As I have said in the PR, its better to configure the port to display dynamically and the user should be able to click the URL to test it. I have done the same in my PR. Please take a look.

**Comment by chirag-jn** [comment]
@mohdomama, basically you are also displaying the port number 8080 because http_server.server_port is already fixed to 8080. And it can cause problems if you try to initialise multiple instances of the server from the same IP address. What we can do is choose random port numbers from the available ones if that doesn't cause problem. 
@Mec-iS, please tell, in any case, will user to try to run multiple instances?

**Comment by chrizandr** [comment]
> in any case, will user to try to run multiple instances?

Yes, they would, in fact, the hydra-flock demo is a simulation that uses multiple instances of Hydrus running on different ports.
