### ISSUE TITLE
Repetition of code

### ISSUE THREAD

**Issue by anubhav253** [HTTP-APIs/hydrus#120]
### I'm submitting a 
- [x] Code optimization.

### Current Behaviour:

This Logic to check whether a http request made is authenticated or not is repeated inside every CRUD operations.This whole logic is repeated at 8 places. Few samples are provided here.

https://github.com/HTTP-APIs/hydrus/blob/f88d0d06933ec0d426bd7d6df51f2972fd389a40/hydrus/app.py#L103

https://github.com/HTTP-APIs/hydrus/blob/f88d0d06933ec0d426bd7d6df51f2972fd389a40/hydrus/app.py#L131

https://github.com/HTTP-APIs/hydrus/blob/f88d0d06933ec0d426bd7d6df51f2972fd389a40/hydrus/app.py#L169

### Expected Behaviour:

Their should be a single function to check the authentication called by each CRUD operation.

### Do you want to work on this issue?

yes

**Comment by chrizandr** [comment]
That function is a flag to check whether authentication is required for the server to respond or not. It does not check the authentication headers, that is done by check_authorization. Variables in Hydrus are set using application contexts and you need setter and getter functions to read and modify them. These contexts are also not accessible from outside the app, like in the CRUD operations for example. Also since each different type of request is handled by different functions[get, put, post and delete] all these functions need to check if authorization is needed. Although the check of the authorization header can be done outside the app, in a single function, checking the flag is needed in every instance.

Summing it up, that function doesn't check the authorization headers, it just checks the flag for request handling.

**Comment by anubhav253** [comment]
@chrizandr  - Yeah i got that there are two function named **get_authentication** and **check_authorization**  one to check whether the authentication required and other to actually check the authorization. but here what i have done is moved entire block of this authentication logic to a function. which is being called at every instances. (GET, PUT, P0ST, DELETE) - I have not removed the get_authentication login and check_authorization logic from anyone of them. Rather i am referring to a function for everyone of them. May be if i misunderstood something please help me to rectify it.

**Comment by xadahiya** [comment]
Discussion continued in https://github.com/HTTP-APIs/hydrus/pull/121

**Comment by Mec-iS** [comment]
This converged into #123
