### ISSUE TITLE
Mapping Hydra Objects to OpenAPI Objects.

### ISSUE THREAD

**Issue by chrizandr** [HTTP-APIs/hydrus#193]
Hydra representations of Objects needs to be mapped with OpenAPI objects.

The end goal is that given an OpenAPI Spec, we can generate an equivalent Hydra API Documentation that represents an API with the same functionality.

All discussions from #149 apply here.

Please specify features of the OpenAPI spec and we can discuss equivalent functionality in the Hydra spec.

**Comment by vaibhavchellani** [comment]
In OAS they reference the type of object they want in param from the definitions of objects the user defines in the doc . 
View [this](editor.swagger.io) for example 
How do i implement the readOnly, writeOnly here ?

Right now i am parsing the "classes" , making them the "title" of definitions and  "supportedProps" the "properties" . How do i put access control on this ?

The solution i have in mind is defining multiple definitions according to readOnly and witeOnly , then refer those when required instead of the whole class .
For example if a class has password and username as properties where password is readable:false , i will make another definition with no password property and reference it with a "GET" request .

**Comment by chrizandr** [comment]
Could you give an example for more clarity? The link you provided does not seem to be working.

**Comment by vaibhavchellani** [comment]
i updated the link , sorry for that . 
Now that we are going for Open Api -> Hydra , i think i wont face this issue , will ask again if i do .

**Comment by Mec-iS** [comment]
https://github.com/HTTP-APIs/hydra-ecosystem-wiki/issues/36
