### ISSUE TITLE
Define the "user-experience" flow from RDF to HYDRA to API data, and different possibilities about

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#21]
There are different approaches to be tried about how the user approaches the definition of his/her API.

The procedure we need to implement can be realized as:
* a flow from the metadata to the data (define RDF doc first)
* a flow from API-metadata (HYDRA) to the data (define HYDRA `ApiDocumentation` first)
* a mixed approach (RDF plus HYDRA)

Check how this flow is handled in Levanzo.

Check official use cases: https://github.com/HydraCG/Specifications/commits/master

**Comment by chrizandr** [comment]
Levanzo's implementation supports definition of the `ApiDocumentation` in the code itself and links routes to Hydra classes and Properties in code too. Here is an example:
```clojure
(def sorg-Person (hydra/class {::hydra/id (sorg "Person")
                               ::hydra/title "Person"
                               ::hydra/description "A person"
                               ::hydra/supported-properties
                               [(hydra/supported-property
                                 {::hydra/property sorg-name})
                                (hydra/supported-property
                                 {::hydra/property sorg-email
                                  ::hydra/required true})
                                (hydra/supported-property
                                 {::hydra/property vocab-password
                                  ::hydra/required true
                                  ::hydra/writeonly true})
                                person-address-link]
                               ::hydra/operations
                               [(hydra/get-operation {::hydra/returns sorg-Person})
                                (hydra/delete-operation {})]}))
```
I propose to implement a similar approach, but rather than having a user type the code for definitions, we ask for the `ApiDocumentation` itself.

Since routes for the resource would be in the document as well, the user need not explicitly define routes unless he chooses to do so. 

Here is a flow diagram of this method:

![a](https://user-images.githubusercontent.com/10355740/27012531-cc015c0a-4eee-11e7-9d0c-11b5308f1b2c.png)

I have already written a starting script for such a parser in `develop/hydrus/data/doc_parse.py`.

Since our core vocabulary needs to be Hydra, I think that we should focus more on this as compared to an RDF based input.

An extension for an RDF based input can added using the script I wrote in `develop/hydrus/hydraspec/parser.py`.
This script takes an `Owl/RDF` based `JSON-LD` document and generates a Hydra `APIDocumentation` for the same. 
Combining this, we could create a workflow for RDF as follows:

![b](https://user-images.githubusercontent.com/10355740/27012579-e9336e7a-4eef-11e7-9dbe-e3df4ce496d4.png)

Please comment :)

**Comment by Mec-iS** [comment]
Going on with #11 and #54

**Comment by Mec-iS** [comment]
The workflow draft is been worked at https://github.com/HTTP-APIs/hydra-ecosystem-wiki/blob/master/Workflow.md

**Comment by Mec-iS** [comment]
In progress at https://github.com/HTTP-APIs/hydra-ecosystem-wiki/issues/16

**Comment by Mec-iS** [comment]
The basics of the user experience have been defined in the wiki
