### ISSUE TITLE
Set up "hydra:search" endpoints to filter items/ids (IRITemplate)

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#302]
### I'm submitting a 
- [x] feature request.

### Current Behaviour:
As discussed in this issue in the Specs https://github.com/HydraCG/Specifications/issues/168#issuecomment-404415370
hydrus should provide an endpointbased on `hydra:search` to introspect/filter items and ids. In particular:

### Expected Behaviour:
As described in the issue mentioned above:
> A better way for the client to discover the ID of an object would be, IMHO, to query the server for that object based on functional dependencies. E.g.: find the book with ISBN 123456 ; find all sensors on network X with serial number Y. That way, the client does not have to know how the server generates ID, and the server does not have to commit forever to a given way of generating IDs. All the server has to do is to provide the "search" functionality described above.

**Comment by knakul853** [comment]
@Mec-iS  i read the above mentioned link and bit confuse with the feature what exactly you have requested.
is it only just a mechanism to search the endpoints to filter items/ids  . i guess <br>  ```hydrus  should provide an endpointbased on hydra:search to introspect/filter items and ids. In particular: ```  this should be in expected Behaviour section:<br>need bit guidance related to this feature

**Comment by knakul853** [comment]
i already checked out btw  thanks @de-sh 
is not this sould be in  expected behaviour section ```hydrus should provide an endpointbased on hydra:search to introspect/filter items and ids```

**Comment by knakul853** [comment]
@Mec-iS  thanks

**Comment by Mec-iS** [comment]
you can try looking into the mailing-list archive, for example: https://lists.w3.org/Archives/Public/public-hydra/2016Nov/0000.html

Best way is to go through examples and then try to write to the mailing-list asking for specific questions.

**Comment by Mec-iS** [comment]
New page on the doc about: http://www.hydraecosystem.org/IriTemplate

**Comment by Guttz** [comment]
Useful links detailing the interaction between server and client regarding search functionality:

- https://github.com/HydraCG/cookbook/blob/master/drafts/7.searching-events.md
- https://github.com/HydraCG/cookbook/blob/master/drafts/8.filtering-events.md

**Comment by Mec-iS** [comment]
NOTE: obviously the IRITemplate endpoint should make pagination available

**Comment by vddesai1871** [comment]
>NOTE: obviously the IRITemplate endpoint should make pagination available

Regarding pagination, as discussed here http://www.hydra-cg.com/spec/latest/core/#client-initiated-pagination hydrus can add `limit`, `offset` and `pageIndex` variables to the IriTemplate attached with collection.
ex.
```js
{
...
...
"search": {
"template" : "endpoint(pageIndex, limit, offset[, other_search_params]",
"mapping": [
{
"@type": ...
"property": "hydra:limit",
"variable": "limit",
"required": false,
},
{
"@type": ...
"property": "hydra:offset",
"variable": "offset",
"required": false,
},
{
"@type": ...
"property": "hydra:pageIndex",
"variable": "pageIndex",
"required": false,
}
]
...
}
...
}
```
So client have two ways to paginate i) `offset and limit` and ii) `pageIndex and limit.`
1) I don't think it would be a valid case but if by mistake somehow client sends both `offset` and `pageIndex`. Should hydrus provide a warning message(as these pair of parameters is not compatible)  or we can just go with ignoring one of the parameters.

Other interesting issue:
I am assuming that "search" field of collection response can only have one IriTemplate, which I think might be wrong. If it is so, we can provide an array of IriTemplate as value of "search", so one IriTemplate may provide standard search, second one might provide pagination with `limit` and `offset` variables and third one can provide pagination by `pageIndex` and `limit`. Is it possible? (I think it is perfectly doable, a client programmed to search collection by providing `limit` and `offset` can search collection response body for the IriTemplate having mapping with property `hydra:limit` and `hydra:offset` then it can map values to variable names. So in short instead of setting "search" to IriTemplate object, we'll set it to list of IriTemplates.)

**Comment by Mec-iS** [comment]
> I don't think it would be a valid case but if by mistake somehow client sends both offset and pageIndex. Should hydrus provide a warning message(as these pair of parameters is not compatible) or we can just go with ignoring one of the parameters.

Probably we should return status `400` with a proper error message and maybe a link to the spec in the message.

At the moment the range for `hydra:search` is a `IRItemplate` not a list of them:
```
    {
      "@id": "hydra:search",
      "@type": "hydra:TemplatedLink",
      "label": "search",
      "comment": "A IRI template that can be used to query a collection.",
      "range": "hydra:IriTemplate",
      "domain": "hydra:Resource",
      "vs:term_status": "testing"
    },
```
I suggest you to open a issue on https://github.com/HydraCG/Specifications/issues as it may be a good idea.

**Comment by vddesai1871** [comment]
>At the moment the range for hydra:search is a IRItemplate not a list of them:

Yeah but I don't think that prevents it from having list of IriTemplates.

For example take a look at `hydra:mapping` it has `IriTemplateMapping` as range but takes lists of `IriTemplateMapping`.(Look at any examples of it over here http://www.hydra-cg.com/spec/latest/core/#templated-links or in the use cases.)
```js
{
      "@id": "hydra:mapping",
      "@type": "rdf:Property",
      "label": "mapping",
      "comment": "A variable-to-property mapping of the IRI template.",
      "domain": "hydra:IriTemplate",
      "range": "hydra:IriTemplateMapping",
      "vs:term_status": "testing"
}
```
Another similar example is `hydra:possibleStatus`. Which takes list of `hydra:Status`.
```js
{
      "@id": "hydra:possibleStatus",
      "@type": "hydra:Link",
      "label": "possible status",
      "comment": "A status that might be returned by the Web API (other statuses should be expected and properly handled as well)",
      "range": "hydra:Status",
      "domainIncludes": ["hydra:ApiDocumentation", "hydra:Operation"],
      "vs:term_status": "testing"
}
```
