### ISSUE TITLE
Revamps in Hydrus

### ISSUE THREAD

**Issue by aribalam** [HTTP-APIs/hydrus#358]
There are a list of things in Hydrus that I think needs some discussion. So I am opening a new issue about it.

1. When creating a `GraphIAC` relation, the value of property inserted by the client is a class name which could create conflicts in the meaning of the value (the client meant it as a string value, the server would interpret it as a reference to a class). I think it would be more appropriate to use an id or a value which has a clear semantic that it refers to a class.
2. The properties entered in the database are unique by name. We can have a property whose semantic would depend on the class it is used on. (eg. A property may be abstract for one class, an instance property for another)
3. A property entered in the database has no pre-defined type. Its type is dependent on its value, the first time it is used to insert an object in the server.
4. #226 made sure that all the required properties are present while inserting an object. But we have no checks to make sure that no property is inserted which are not supported by a class (i.e which is not present in the `supportedProperty` list of a class)

**Comment by vddesai1871** [comment]
>When creating a GraphIAC relation, the value of property inserted by the client is a class name which could create conflicts in the meaning of the value (the client meant it as a string value, the server would interpret it as a reference to a class). I think it would be more appropriate to use an id or a value which has a clear semantic that it refers to a class.

I don't think using IDs will be the proper way to handle this, as I think clients are not supposed to know (or function on the knowledge of) which IDs server is using internally. One approach comes to my mind is --- clients should use a prefix when passing class as a property value, something like "vocab:Drone"(I don't think it will be semantically ambiguous anymore), then the server can strip off the prefix and search for the class as it does currently.

>The properties entered in the database are unique by name. We can have a property whose semantic would depend on the class it is used on. (eg. A property may be abstract for one class, an instance property for another)

I can't think of any such case, it would an example of a very poor API design. Can you give any example of such cases?


>#226 made sure that all the required properties are present while inserting an object. But we have no checks to make sure that no property is inserted which are not supported by a class (i.e which is not present in the supportedProperty list of a class)


In crud.py, before inserting any new value, it is checked whether the property is stored in the db or not, but yes it seems like a client can add Class A's supportedProperty to an instance of Class B.

**Comment by aribalam** [comment]
> I can't think of any such case, it would an example of a very poor API design. Can you give any example of such cases?
Me neither. Although I think there might be some predicates whose meaning depends on the context or subject we are using upon.

> before inserting any new value, it is checked whether the property is stored in the db or not
Agreed. But should not we have an additional check to remove all properties that are not supported by the class whose instance we are inserting?

**Comment by chrizandr** [comment]
Here are a few comments:

1. GraphIAC uses the internal class IDs to link the classes, not strings, so there is no ambiguity there. If you see the models, it is listed as a foreign key. Also, **like I said before** none of the models that include classes: GraphCAC, GraphIAC; are accessed by the client. This data is not served at any endpoints so there is no actual need for them to have IDs. They are for internal use only to define the graph. We still don't have a use case for them. 
2. Most semantic properties, both RDF and OWL based ones have a domain and range attribute defined, of course to implement these constraints on properties we would have to dereference the URIs and parse the property definitions to be able to find the correct subject and object for the defined property. Right now, all we need to make sure is that the property is used as per the API Doc, we need not worry about their "actual" definitions, more on this in point 4.
3. This is correct, because we don't really know the kind of subjects/objects that the property uses(It is not defined in the API Doc, not always). So we guess the properties type based on the data. This was more of a workaround back when I was trying to figure out how to assign a type to the property. I think we can find a more robust method for this. Let's try and come up with some solutions and we can discuss on here.
4. This is an important thing that we need to work on. I have already mentioned in some previous issues that we can have a `API_Doc.validate()` method that does all the sanity checks needed for an object.

**Comment by Mec-iS** [comment]
@aribalam what is the status of this? after the discussion, what are the improvements that it is still worth considering?

**Comment by aribalam** [comment]
@Mec-iS. I think we have an option. On the basis of the link provided by @chrizandr ([http://www.linkeddatatools.com/properties](url)) 

I propose that we add an additional parameter `range` to property that would define the type of values the property can hold. We can provide a list of values to define it. For example - 

`{
    property: 'property_name'
    range: ['ABSTRACT', 'INSTANCE']
   ....
}` 

This is already been done in OpenAPI specifications ([https://swagger.io/docs/specification/data-models/data-types/](url)). It would solve the problems mentioned in 2. and 3. 
Moreover, we could also make a property flexible if it has been provided with a missing `range` parameter and no checks will be performed on it during insertion of an object in `crud.py`. However, this could make the server prone to errors.

**Comment by chrizandr** [comment]
We don't add anything to the API documentation that is not defined in the Hydra spec. 

Properties that are stored in the API will mostly be defined in the API doc itself, these can be verified on the server side. Those that are not stored in the API, will have a URI provided for them, we don't worry about these, because it is a link to where the actual object is. Dereferencing and verifying the content then falls upon the client.

As far as I can see, I don't really consider this to be a major problem. Like I mentioned before, just worry about the validate method to check that API doc constraints are met. We cannot add things to the documentation as we please, we need to adhere to the spec.

**Comment by Mec-iS** [comment]
As Chris specified, we cannot add anything to the ApiDoc that is not in the spec.

We may do this by adding a configuration module to the server and the client (something like the Django `settings.py` module in which the variables in the module are readable as dict-like keys). I suggest to try to generalize the problem, like asking yourself: beside properties, how this problem could be solved for classes or other elements? (like, if a developer wants to customize the behaviour for a certain element). Briefly, it may be an option to try to tackle an higher-order problem so we can design a configuration module for both hydrus and the agent.

**Comment by Mec-iS** [comment]
About https://github.com/HTTP-APIs/hydrus/issues/358#issuecomment-477025040

This kind of long reply are really well suited to become part of the documentation, if they are not yet. Please consider opening a PR on `http-apis.github.io` adding this information in the right file or creating a new file.
