### ISSUE TITLE
Create tests for Hydrus CLI

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/hydrus#361]
### I'm submitting a 
- [x] bug report.
- [x] feature request.

### Current Behaviour:

Currently, the test suite doesn't cover `cli.py`. 
### Expected Behaviour:

The test suite should include tests for all major modules.
### Steps to reproduce:

See `hydrus/tests`
### Do you want to work on this issue?

NO

**Comment by invinciblycool** [comment]
Taking this up!

**Comment by invinciblycool** [comment]
@xadahiya While writing tests, invoking [startserver](https://github.com/HTTP-APIs/hydrus/blob/develop/cli.py#L40) using [CliRunner](http://click.palletsprojects.com/en/6.x/testing/) does not allow any tests to run since `serve_forever()` method is blocking. This is largely different from the mocking done for the app in `test_app` since there was no such single function which was calling a blocking method. Any ideas?

**Comment by de-sh** [comment]
As part of working on this I think we can also considering moving out the PEP8 test and working on making cli.py compliant with it.

**Comment by knakul853** [comment]
test is added now you can close this

**Comment by Mec-iS** [comment]
only the test for running the server has been developed. Has the CLI other subcommands?

**Comment by knakul853** [comment]
in startserver() we are using all the CLI commands so testing it doesn't imply testing it's subcommand
please clarify

**Comment by chrizandr** [comment]
@Mec-iS @xadahiya Is this good to close?

**Comment by chrizandr** [comment]
Merged in #376
