### ISSUE TITLE
Change response message structure

### ISSUE THREAD

**Issue by vddesai1871** [HTTP-APIs/hydrus#392]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:

Right now hydrus returns a string as response message which contains the information related to object's ID. If the client wants to access that, it has to use a regular expression to extract the ID from the message.
### Expected Behaviour:

We can return a response in which object ID is separated from the verbal message, so a client can access it directly.
Ex. 
```
{
"message": "Object successfully created",
"object_id": "deede-w9d2wo-dkwd-fefrr3rt4"
}
```

@Guttz anything you want to add?
### Do you want to work on this issue?

YES

**Comment by Guttz** [comment]
That's what I think is important for now. I guess a third value as the timestamp may turn out to be necessary in the future for sync conflicts, but if it eventually appears as crucial we do it. Thanks, @vddesai1871!

**Comment by Mec-iS** [comment]
also adding a boolean in a `error` key if the status code is not 2xx or 3xx would be nice to have

**Comment by chrizandr** [comment]
Does the spec say anything about the format of response messages? We should find that out. 

Alternatively, we can return the modified object in case of PUT/POST. For DELETE the status code should be sufficient. The reason being that we would have a more standard response rather than ambiguous messages that we need to parse or custom objects where we define our own fields.

Also since all responses are HTTP responses, they have status codes by default. Unless there is an error we should use code 200 for responses. We already have appropriate status codes based on the error implemented in the exceptions.

**Comment by vddesai1871** [comment]
Yes following the spec would be the best option to go.
As I mentioned in the issue the issue was created to separate the object ID from the textual message. 
So according to spec(the portion you linked in the other issue), we can directly return a `Status` or `Error` object in the response. And looking at the example given there and looking at core.jsonld (the actual vocab) the response will look something like
```
{
 "@context": "../../abc.jsonld",
 "@type": "Status",
 "title": "Instance creation successful",
 "description": "Instance with ID X successfully created."
}
```
It's certainly better but how can I separate the ID from the description message? It will probably involve adding an extra non-standard field. If I am not wrong the only time a client can get the benefit of separated ID is when it creates a new object. So should we add the extra field for object_id or just use the current response mechanism adjusting it to the spec format?

**Comment by chrizandr** [comment]
The spec mentions subclassing the Error and Status classes. It also allows us to add additional identifiers to the messages. 
> Furthermore, a Status or Error returned by the server can also be given an identifier.
This means we can use the `@id` field in status and objects to provide URIs. In case of PUT/POST these can represent the URI for the instance. For DELETE, I don't think we really need an ID in the response since the instance with that ID would have been deleted, just a 200 response would be enough.

**Comment by vddesai1871** [comment]
>This means we can use the @id field in status and objects to provide URIs. In case of PUT/POST these can represent the URI for the instance. For DELETE, I don't think we really need an ID in the response since the instance with that ID would have been deleted, just a 200 response would be enough.

While coding this I found out we are already following the exact procedure you mentioned with the help of the "Location" header. So that solves the `id` issue. I am going with the response structure I mentioned above to close this and resolve #396.

**Comment by Guttz** [comment]
Seems to be working. Thanks for clarifying @vddesai1871!

![Group 3 (3)](https://user-images.githubusercontent.com/11739405/58961005-9aa0dd80-87a8-11e9-8f40-49e720f5339d.png)

**Comment by Mec-iS** [comment]
Moved to #396
