### ISSUE TITLE
[Question] Custom Backend

### ISSUE THREAD

**Issue by iddan** [HTTP-APIs/hydrus#401]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:
Currently hydrus is only integrated with SQLAlchemy as a backend.

### Expected Behaviour:
Allow providing a backend that complies to a defined API

### Do you want to work on this issue?
Yes

**Comment by Mec-iS** [comment]
Thanks for opening a feature request.

can you be more specific in what you want to achieve? hydrus uses by design choice an SQL database; SQLalchemy allows plugging in the most popular SQL databases (with some caveats about dialects). Do you mean allowing hydrus to use a key-value or document store? Or allowing usage of different ORMs?

**Comment by iddan** [comment]
Actually I'm curious about integrating it with a triple store. I want to expose a hydra API on top of a graph DB / API.

**Comment by Mec-iS** [comment]
You can have ideas about scenarios by going through [this document](https://www.hydraecosystem.org/Design). According to how we are engineering the client-server implementation, we have defined the server `hydrus` as pure HTTP REST server and because of that SQL is the perfect match for this design (HTTP verbs map to CRUD operations and queries in the database). 
The actual graph that will hold the relations and represent the connected data network is present in the *client* or Hydra-agent (see [**`hydra-python-agent`** repository](https://github.com/HTTP-APIs/hydra-python-agent)), this because Hydra allows rich/smart clients and that is what we want to leverage; in this area we are currently experimenting using  OpenCypher to query a Redis-graphlib backend. Considering this, you may want to attach any graph db or triples store *to the agent*, the server is supposed to be SQL as I said, with some room for storing external references for the sake of, in future, allowing dereferencing (for this purpose see [Data storage](https://www.hydraecosystem.org/Design#data-storage) paragraph). The client can for sure support any backend that is able to store/query a graph.
