### ISSUE TITLE
[DISCUSSION] Updating collections

### ISSUE THREAD

**Issue by sameshl** [HTTP-APIs/hydrus#494]
After PR https://github.com/HTTP-APIs/hydrus/pull/488, we have support for collections as a resource.
Therefore, now we need to see how we go about updating(**POST** operation) individual collections.

In PR https://github.com/HTTP-APIs/hydrus/pull/488, the **POST** operation works by needing to add all the members of the collection in the request body even for updating one of the members.
This might not be the most efficient way to go about it. We might think about having a specific endpoints for adding / deleting members from a given collection.

We need to see the spec at hydra-cg to see how to go about updating members of collections.

**Comment by Mec-iS** [comment]
resources should be addressed (with any CRUD operation) by using the URIs dedicated to the instance of the given type, i.e. `POST /serverapi/Drone/1` or `PUT /serverapi/Drone/100`

**Comment by chrizandr** [comment]
@Mec-iS this is not related to the resource. This is related to a collection. How do we add and remove objects from custom collections without having to delete and create the entire collection again.

**Comment by Mec-iS** [comment]
@chrizandr by adding to the type that the collection refers to.

If a custom collection that points to a subset of `Drone` objects is created (using a templated that applies a filter), the members of the collection can be added/removed by doing CRUD operations the `Drone` class instances. If I remember well, custom collections are templates that apply some sort of filter, if the newly added instance comply with the filter, it will appear in the collection; removing from a custom collection can happen if:
* the instance is removed (so it cannot be filtered out from the type because it is not in the original collection)
* some prop in the instance is changed in a way that it does not comply anymore with the filter  (so i cannot be filtered as it is not part of the query anymore).
Please explain if I am wrong.

**Comment by chrizandr** [comment]
All collections now contain only links and with the migration to models based on the API documentation rather than general ones, we already have these two cases handled in by the database.

Right now custom collections are basically a set of links. The question here is how to efficiently modify this collection of links. Right now the way it is being done is that if we want to update a collection, we need to delete the entire collection and add a new collection to the database with the modified members. This is extremely inefficient if we only want to add/remove one object from the collection. Requests to update the collection must also include all the members of the collection. 

This issue is to discuss how we can implement this more efficiently.

**Comment by Mec-iS** [comment]
can you provide a link to the spec?
Once we have templates and filters, what are the use-cases for custom collections?

> The burden of what the collection must contain falls on the client.
do you mean this should be implemented in `hydra-pythoin-agent`?

**Comment by chrizandr** [comment]
https://www.hydra-cg.com/spec/latest/core/#collections

The spec defines a collection as 
> resources that reference a set of somehow related resources

Nowhere in the spec is it mentioned that a collection is limited to only the set of **all** resources in the API. That was a feature that was seen in Markus's API which was used as reference during the initial phase. The spec allows collections to be arbitrary. 

This is also highlighted in the example given in the spec[Example 19]. The use case is mentioned in this example itself.
```
{
  "@context": "http://www.w3.org/ns/hydra/context.jsonld",
  "@id": "http://api.example.com/an-issue/comments",
  "@type": "Collection",
  "manages": {
    "subject": "http://api.example.com/an-issue",
    "property": "http://api.example.com/vocab#comment"
  },
  "member": [
    {
      "@id": "/comments/429"
    }
  ]
}
```
Here the above collection references a set of comments related to **one** issue mentioned as `http://api.example.com/an-issue`.  For each **separate** issue we will have a different collection of comments. This was also the use case discussed in the original issue for Collections as a resource #416 

Hope this clears any confusion.

**Comment by Mec-iS** [comment]
#554 will be merged soon
