### ISSUE TITLE
/serverapi/vocab should allow reaching fragments

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#512]
### I'm submitting a 
- [x] bug report.

Two different related issues here:

### Current Behaviour:
1. `/serverapi/vocab#Area` returns the full vocabulary.
2. at `http://localhost:8080/serverapi/contexts/EntryPoint.jsonld` see: 
```{
"@context": {
"Area": {
"@id": "http://localhost:8080/serverapi/vocab**#EntryPoint/Area**",  <<<<<
"@type": "@id"
},
```

### Expected Behaviour:
1. `/serverapi/vocab#Area` should return the `Area` object (with context) only, not the full vocabulary, i.e.:
```
{
  "@context": { ... },
  "@id": "http://localhost:8080/serverapi/vocab#Area",
  "@type": "hydra:Class",
  "description": "Class for Area of Interest of the server",
  "supportedOperation": [
   ....
```

2. ids in `http://localhost:8080/serverapi/contexts/EntryPoint.jsonld` should link to `serverapi/vocab#` fragments like `@id": "http://localhost:8080/serverapi/**vocab#Area**"`

**Comment by raoashish10** [comment]
@Mec-iS I have been trying to work out a solution for this issue but I haven't gotten far. I feel like the issue here is the use of '#'. Maybe the string ahead of serverapi/vocab gets ignored? I tried changing it to a '/' instead in the '@id' key but it gave me an error saying that no such link exists which kind of confuses me because I have provided the link in the '@id' key

**Comment by Mec-iS** [comment]
the idea is to provide for the JSON-LD a feature that is availalble in HTML pages. For example if you write this link into you browser `https://en.wikipedia.org/wiki/Representational_state_transfer#Layered_system` you are redirected to the paragraph "Layered_system" inside the linked page. The same should happen for the JSON-LD, if a fragment is specified, the server should return only the object requested.

Here it is a way you can implement this:
1. create a Flask decorator that reads the path for the request (`Request` object, `from flask import request`); if a fragment name is present in the request (you can use a regular expression to match the fragment name or simply read the URI backward up to the `#`; first one would be more solid) tell the handler to return only the context plus the object specified by the fragment name
2. apply the decorator to the view that returns the JSON-LD

**Comment by raoashish10** [comment]
@Mec-iS Understood! I will try implementing it and sending in a PR

**Comment by raoashish10** [comment]
@Mec-iS I have been trying to make a decorator which reads the URI but I have come across an issue. I am unable to extract the fragment identifier from the request URI because I think flask just cuts off the string after the hash on the server side. 
For eg: ```vocab#Drone``` becomes ```vocab```. After some digging up, I found that the fragment cannot be retrieved on the server side. I think that instead of using  fragment identifiers, switching to sending parameters may be a better idea or adding the fragment texts (Drone,Area) in the URI itself Eg: ```vocab/Drone```. Or is there a work-around for this issue?

**Comment by Mec-iS** [comment]
Sorry I forgot about this part of [RFC](https://tools.ietf.org/html/rfc3986#section-3.5).
we need to take a look into how RDF servers implement this feature.

@chrizandr @sameshl any observation?

**Comment by aryanag1971** [comment]
can I work on this issue?
