### ISSUE TITLE
Define and implement a way to set right column types when auto-generating the database

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#581]
### I'm submitting a 
- [x ] feature request.

### Current Behaviour:
All database columns are set to `db.String` as Hydra do not require specifying the type of variable for a filed

### Expected Behaviour:
Database columns should be created with `dbString`, `db.Integer` or `db.Float` according to types defined in the ApiDoc or Ontology via properties like `"@type": " "xsd:decimal"` as discussed in https://github.com/HTTP-APIs/creditrisk-poc/issues/6

I can work on this but I need support from @sameshl

**Comment by Purvanshsingh** [comment]
I think while creating supported properties in API_doc via `doc_writer.py` we should provide an option to the user to mention the property type. which could be passed to `db_models.py` and appropriate columns can be created.
@farazkhanfk7 what are your views on it?

**Comment by Mec-iS** [comment]
if the property is present in the original ontology, we just copy them in the ApiDoc (to be done in `hydra-python-core`) and then in `hydrus` make [this function](https://github.com/HTTP-APIs/hydrus/blob/develop/hydrus/data/db_models.py#L144) to consider the copied value to create the column.

I open the related issue in `hydra-python-doc`.

**Comment by Purvanshsingh** [comment]
But I have a concern about how we will be able to fetch type from such URIs ( https://schema.org/name )

**Comment by Mec-iS** [comment]
https://schema.org/name is a label/name so by definition is a String

**Comment by sameshl** [comment]
@Mec-iS Have you thought about how we are going to map `properties` in the api_doc to the type of column(`db.String`, `db.Integer` or `db.Float`) we need?

**Comment by Mec-iS** [comment]
as I mentioned we are going to copy them from the original ontology to the ApiDoc and then read them from the ApiDoc in hydrus when the tables are generated.

**Comment by chrizandr** [comment]
Is there any use for us to store them as integer or floats when all hydrus is doing is serving the data? 

We do not process the data in any form, just store and serve it when needed. I agree that it makes more sense, but the reason we avoided that is because there are multiple numerical datatypes in different Ontologies, and it would be difficult for us to map all of them. For example, apart from `xsd:integer` or `xsd:decimal` there are also types like `xsd:nonNegativeInteger`, `xsdx:integerLessThanN` which also are supposed to be numerical datatypes.

I'm just wondering if there is any additional use for us to store them as values other than it being semantically correct.

**Comment by Mec-iS** [comment]
> Is there any use for us to store them as integer or floats when all hydrus is doing is serving the data?

There are major cons:
* it is against best practices to not respect types in an SQL database and it is a huge waste of memory. It is against the basics of database normalisation.
* JSON standard supports the types int and float, and therefore they must be represented with the right type. It would be basically misusing serialisation.
* payloads that deliver numbers as strings break conventions with all existing clients.

**Comment by open-risk** [comment]
The graphql api approach to data types could be a [good guide](https://graphql.org/graphql-js/basic-types/)

**Comment by chrizandr** [comment]
Right now, hydrus assumes that every property is either a string literal or a URI pointing to a resource. In both cases, they are stored as strings in the database. So for example if we have a property for `temperature` that is supposed to have a number, hydrus doesn't check if the value sent to it is a number or not. It will store a URI if we send a URI in that field. 

When creating the tables in the database, we are not checking the `@type` field for a given supported property defined in the API documentation. We can implement this check when the database is being created or when the request/response is being processed. We say that we add support for the core RDF datatypes in hydrus. Whenever a supported property is a literal, it can be defined in the API documentation with one of these four types: "xsd:string", "xsd:boolean", "xsd:decimal", "xsd:integer".

So suppose a property is defined as:
```
{
"name": "Temperature",
"@type": "xsd:integer"
}
```
We cast the property as integer. Similarly for the other 3 datatypes. 

In case the datatype is a custom type, it will be defined in the API documentation as :
```
{
"name": "Temperature",
"@type": "http://weather.com/schema/celsius"
}
```
In this case, the property is assumed to have instances of a resource of some existing ontology, and the field would then store only URIs pointing to instances of the resource, which may or may not be in the API. We do not need to derference the `@type`, because hydrus already assumes it to be an instance of some other resource.

Something similar is implemented here already: https://github.com/HTTP-APIs/hydrus/blob/34c909e26e58bf2aee279391c7560d8536ff9f91/hydrus/data/db_models.py#L94

Where the @type is checked to be a resource from the same API doc to add foreign key relations. We just need to add checks below for "xsd:string", "xsd:boolean", "xsd:decimal", "xsd:integer". All other cases would be treated as URIs in the database to be stored as strings.

You can ping me on slack if you need any help.

**Comment by Mec-iS** [comment]
implementation in core: https://github.com/HTTP-APIs/hydra-python-core/pull/91
