### ISSUE TITLE
Error while Setup the Project

### ISSUE THREAD

**Issue by yashLadha** [HTTP-APIs/hydrus#74]
The Project is using some files from inside a package directory, but that directory is not listed as a package due to which it is throwing import error while executing the `main.py` script.

OS : Debian 9
Python 2.7

Screenshot : 
![image](https://user-images.githubusercontent.com/18033231/36127576-3e7d73f2-1084-11e8-8268-19dc6f2cb141.png)

**Comment by alohamora** [comment]
You have to create an empty __init__.py file in each package directory so
that python can access all the modules inside that package.

On 13-Feb-2018 6:08 AM, "Yash Ladha" <notifications@github.com> wrote:

The Project is using some files from inside a package directory, but that
directory is not listed as a package due to which it is throwing import
error while executing the main.py script.

OS : Debian 9
Python 2.7

Screenshot :
[image: image]
<https://user-images.githubusercontent.com/18033231/36127576-3e7d73f2-1084-11e8-8268-19dc6f2cb141.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/HTTP-APIs/hydrus/issues/74>, or mute the thread

**Comment by xadahiya** [comment]
Hey @yashLadha , this is due to the reason that you're using `Python 2` instead of `Python 3`. 

`A package is a group of related modules that function as a single entity. In Python 2, when modules within a package need to reference each other, you use import foo or from foo import Bar. The Python 2 interpreter first searches within the current package to find foo.py, and then moves on to the other directories in the Python search path (sys.path). Python 3 works a bit differently. Instead of searching the current package, it goes directly to the Python search path. If you want one module within a package to import another module in the same package, you need to explicitly provide the relative path between the two modules. `

As @chrizandr  specified `we always treat Hydrus as a package and import using the complete paths`.
I'll add python3 as a requirement in the project WIKI.
Cheers!

**Comment by yashLadha** [comment]
Thanks for sharing this info. I always try to run the project with Python
2, but it will be good if that instruction is in the README. I will send a
PR correcting it. Cheers

On Feb 13, 2018 8:15 AM, "Akshay Dahiya" <notifications@github.com> wrote:

Hey @yashLadha <https://github.com/yashladha> , this is due to the reason
that you're using Python 2 instead of Python 3.

A package is a group of related modules that function as a single entity.
In Python 2, when modules within a package need to reference each other,
you use import foo or from foo import Bar. The Python 2 interpreter first
searches within the current package to find foo.py, and then moves on to
the other directories in the Python search path (sys.path). Python 3 works
a bit differently. Instead of searching the current package, it goes
directly to the Python search path. If you want one module within a package
to import another module in the same package, you need to explicitly
provide the relative path between the two modules.

As @chrizandr <https://github.com/chrizandr> specified we always treat
Hydrus as a package and import using the complete paths.
I'll add python3 as a requirement in the project WIKI.
Cheers!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/HTTP-APIs/hydrus/issues/74#issuecomment-365133813>, or mute
the thread

**Comment by xadahiya** [comment]
@yashLadha  you need to run the project using `python3`. I've added this info to the wiki.

**Comment by yashLadha** [comment]
Sure, but mostly new contributors see the README for installation
instructions, can I send a PR stating that information in readme.

**Comment by xadahiya** [comment]
Updated the README

**Comment by yashLadha** [comment]
:+1:

**Comment by Mec-iS** [comment]
For the sake of Python-Hydra's activities, Python 2 should not be considered a supported version. Supported versions starts from 3.5.2 and above. The fact that any of our repos works with lower versions is not guaranteed.
