### ISSUE TITLE
Adding Continuous Integration in Hydra project

### ISSUE THREAD

**Issue by vivonk** [HTTP-APIs/hydrus#84]
As the things are professional so for a good maintenance and productive reports, we should add CI service to the repository.
There are several provider which provides free CI service to open source projects.

**Comment by Mec-iS** [comment]
This is for sure a good idea, but for now we prefer the developers to run the tests locally to get familiar with those and maybe improve them. Running tests multiple times can be a good exercise to know the code.

**Comment by vivonk** [comment]
@Mec-iS that is great but to maintain it on github, how you believe on someones commit that all test cases pass. This may definitely raise a conflict after some commits because the environment that person was using may be different than we are accepting. [This one](https://medium.com/the-making-of-appear-in/why-continuous-integration-is-so-important-7bb63ba5dc57) encouraged me to raise a ticket, give a read to it. 😄

**Comment by Mec-iS** [comment]
Thanks for the article. I know the advantages of CI, this repo is still in a very young phase and I don't think setting up the environment can create much problem of compatibility (considering there are no pre-compiled C-bindings nor even system-level modules): all the libraries are easily installable via simple `pip` commands. Furthermore any Python developer should know the magic commands:
```
$> python3 -m venv venv
# source the enviroment and
(venv) $> pip install -r requirements.txt
```
and recreate the virtual environment for the repo (that is basically what CI provides). Finally the pace and number of contributions at the moment does not really justify CI.

**Comment by vivonk** [comment]
Get it @Mec-iS  but I have still one point for you that how you will believe that someones commit had passes all the tests? even the person did not run the tests on his local. Don't consider me wrong but just want to put my point to you 😄

**Comment by chrizandr** [comment]
I agree with @Mec-iS . A CI would only make sense when you have builds for your code, which would then cause them to become OS or environment dependent and there would be a need to check multiple builds for each. This is not the case for Python packages that use pip, since they depend on wheel packages that are os specific to install. If your system environment is not supported, you would not be able to install all the packages needed for the application. 

I agree on the point that you need to check if test cases pass, but that could easily be done by asking users to submit test case logs along with the PR. There are only a couple of commands that need to be run ( python -m test.py ) and that doesn't require a CI at this stage.

**Comment by vivonk** [comment]
Correct @chrizandr , get it. Thanks for this good reply, so there should be a relay to users to submit testlogs. 👍
