### ISSUE TITLE
Instructions to use virtual environment missing in the README

### ISSUE THREAD

**Issue by ashwani99** [HTTP-APIs/hydrus#90]
The dependencies may conflict with any other modules presently installed in the user's machine. It's better to use a virtual environment to isolate development environments.

**Comment by chrizandr** [comment]
Virtual environments are optional when using any Python based programs. You may install all requirements directly on your main Python paths. For the purpose of the flock demo, it was necessary to use virtual environments and so that was specified in the instructions. The same is not necessary for running Hydrus as a standalone process. Also unless the packages are a downgrade from the current ly installed versions, there will not be any conflict among Python packages or cause any problems if you install new ones.

**Comment by Mec-iS** [comment]
@chrizandr I always give the advice, since `setuptools` and `pip` have been made fully compatible with `venv`, that it is a good practice to use virtual environments every time, unless there is a particular reason for avoiding it (like some low-level code, but these are really rare exceptions).
Pollution of Python libraries space can be a problem, so as far Python 3 provides the `venv` built-in module, it is a good reference to start the README from the `python3 -m venv myenv` command.
